<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>H5_adrHIN</name>
   <tag></tag>
   <elementGuidId>3ad92e57-3b22-4527-9b0f-9d6a3a1a4561</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//article[3]/h5</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
